version: '2'

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
  postgres:
    image: postgres:12.1
    environment:
      # - POSTGRES_DB=drupal
      # - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=password
    restart: always
      