# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  drupal:
    # image: drupal:8.8.2
    build:
      context: .
      dockerfile: Dockerfile
      
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/themes
      - drupal-themes:/var/www/html/sites
    restart: always
  postgres:
    image: postgres:12.1
    environment:
      # - POSTGRES_DB=drupal
      # - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=password
    volumes:
      - drupal-data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data: